#!/usr/bin/env node

import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const contractFiles = [
  ['api/contracts.ts', resolve(root, 'src/app/core/api/contracts.ts')],
  ['db/schema.ts', resolve(root, 'src/app/core/db/schema.ts')],
  ['auth/auth-types.ts', resolve(root, 'src/app/core/auth/auth-types.ts')],
];
const requiredInputs = [
  'ROADMAP2U_STAGE',
  'ROADMAP2U_REGION',
  'ROADMAP2U_USER_POOL_ID',
  'ROADMAP2U_USER_POOL_CLIENT_ID',
  'ROADMAP2U_API_BASE_URL',
  'ROADMAP2U_CONTRACT_HASH',
];
const apiBaseUrls = {
  dev: 'https://api.dev.roadmap2u.com',
  test: 'https://api.test.roadmap2u.com',
  prod: 'https://api.roadmap2u.com',
};

function fail(messages) {
  for (const message of messages) process.stderr.write(`config: ${message}\n`);
  process.exitCode = 1;
}

function contractHash() {
  const hash = createHash('sha256');
  for (const [relativePath, source] of contractFiles) {
    hash.update(relativePath, 'utf8');
    hash.update('\0');
    hash.update(readFileSync(source, 'utf8').replaceAll('\r\n', '\n'), 'utf8');
    hash.update('\0');
  }
  return hash.digest('hex');
}

function quoted(value) {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}

const outputIndex = process.argv.indexOf('--output');
const outputArg = outputIndex >= 0 ? process.argv[outputIndex + 1] : undefined;
const missing = requiredInputs.filter((key) => !process.env[key]?.trim());
const errors = missing.map((key) => `${key} is required`);

if (!outputArg) errors.push('--output is required');

const stage = process.env.ROADMAP2U_STAGE?.trim() ?? '';
const region = process.env.ROADMAP2U_REGION?.trim() ?? '';
const userPoolId = process.env.ROADMAP2U_USER_POOL_ID?.trim() ?? '';
const userPoolClientId = process.env.ROADMAP2U_USER_POOL_CLIENT_ID?.trim() ?? '';
const contractHashInput = process.env.ROADMAP2U_CONTRACT_HASH?.trim().toLowerCase() ?? '';

if (stage && !['dev', 'test', 'prod'].includes(stage)) {
  errors.push('ROADMAP2U_STAGE must be dev, test, or prod');
}
if (region && !/^[a-z]{2}(?:-gov)?-[a-z]+-\d$/.test(region)) {
  errors.push('ROADMAP2U_REGION must be an AWS region');
}
if (region && region !== 'us-east-1') {
  errors.push('ROADMAP2U_REGION must be us-east-1');
}
if (userPoolId && region && !userPoolId.startsWith(`${region}_`)) {
  errors.push('ROADMAP2U_USER_POOL_ID must belong to ROADMAP2U_REGION');
}
if (userPoolClientId && !/^[a-zA-Z0-9]{20,128}$/.test(userPoolClientId)) {
  errors.push('ROADMAP2U_USER_POOL_CLIENT_ID is not a valid Cognito app client id');
}

let apiBaseUrl = '';
const apiInput = process.env.ROADMAP2U_API_BASE_URL?.trim() ?? '';
if (apiInput) {
  try {
    const url = new URL(apiInput);
    if (url.protocol !== 'https:') errors.push('ROADMAP2U_API_BASE_URL must use https');
    if (url.pathname.replaceAll('/', '') === 'v1') {
      errors.push('ROADMAP2U_API_BASE_URL must not include /v1');
    } else if (url.pathname !== '/' && url.pathname !== '') {
      errors.push('ROADMAP2U_API_BASE_URL must not include a path');
    }
    if (url.search || url.hash || url.username || url.password) {
      errors.push(
        'ROADMAP2U_API_BASE_URL must be an origin without credentials, query, or fragment',
      );
    }
    apiBaseUrl = url.origin;
  } catch {
    errors.push('ROADMAP2U_API_BASE_URL must be an absolute URL');
  }
}
if (stage in apiBaseUrls && apiBaseUrl && apiBaseUrl !== apiBaseUrls[stage]) {
  errors.push(`ROADMAP2U_API_BASE_URL expected ${apiBaseUrls[stage]} for ${stage}`);
}

if (contractHashInput && !/^[a-f0-9]{64}$/.test(contractHashInput)) {
  errors.push('ROADMAP2U_CONTRACT_HASH must be 64 hexadecimal characters');
} else if (contractHashInput) {
  const localHash = contractHash();
  if (contractHashInput !== localHash) {
    errors.push(`contract hash mismatch: backend=${contractHashInput} frontend=${localHash}`);
  }
}

if (errors.length > 0) {
  fail(errors);
} else {
  const requireAuth = stage !== 'dev';
  const source = `/**
 * Generated by tools/generate-config.mjs from public AWS deployment values.
 * The tracked version is mock-safe; deployment workflows replace it only in
 * their ephemeral checkout.
 */
export const DEPLOY_STAGE = ${quoted(stage)} as const;
export const BACKEND_CONTRACT_SHA256 = ${quoted(contractHashInput)};

export const GENERATED_APP_CONFIG = Object.freeze({
  backend: 'aws' as 'mock' | 'aws',
  requireAuth: ${requireAuth},
  aws: Object.freeze({
    region: ${quoted(region)},
    userPoolId: ${quoted(userPoolId)},
    userPoolClientId: ${quoted(userPoolClientId)},
    apiBaseUrl: ${quoted(apiBaseUrl)},
  }),
});
`;
  const output = resolve(process.cwd(), outputArg);
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, source, 'utf8');
  process.stdout.write(`${output}\n`);
}
